### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by freifrauvonbleifrei** [hirschsn/batch-job-indicator#10]
Hi, just tested this:
```
pollinta@lapsgs15:~/Desktop/batch-job-indicator$ PYTHONPATH=".:$PYTHONPATH" ./bji.py hazelhen
[Hazelhen] Job 2452239.hazelhen-batch state: H
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "./bji.py", line 45, in run
    jparser.parse(p.stdout.readline())
  File "/home/pollinta/Desktop/batch-job-indicator/machines/hazelhen.py", line 26, in parse
    self._handle_job(jobid, state)
  File "./bji.py", line 35, in handle_job
    self.jobs[jobid] = JIndicator(jobid, state, self.close_callback)
  File "/home/pollinta/Desktop/batch-job-indicator/jindicator.py", line 42, in __init__
    "Job-Indicator", _ICONS[state], category=appindicator.IndicatorCategory.APPLICATION_STATUS)
KeyError: 'H'
```
so it's printing the first job but seems to have trouble displaying it as icon... did I miss some dependency here? had to install `libappindicator3-dev` in already.

**Comment by hirschsn** [comment]
You did not miss anything, job status "hold" is not recognized/implemented.
Not only should H be recognized properly, aborting with a stack trace on an unknown job status is also a bug.

**Comment by hirschsn** [comment]
A "H" icon should now show up. And if you devise more unknown job states, a "?" should show up.

**Comment by freifrauvonbleifrei** [comment]
not sure if this is the same issue - feel free to move:
```
pollinta@lapsgs15:~/Desktop/batch-job-indicator$ PYTHONPATH=".:$PYTHONPATH" python2 bji.py hazelhen
(Re-)opening remote connection.
[Hazelhen] Job 2453592.hazelhen-batch state: H
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "bji.py", line 68, in run
    jparser.parse(p.stdout.readline().decode())
  File "/home/pollinta/Desktop/batch-job-indicator/machines/hazelhen.py", line 26, in parse
    self._handle_job(jobid, state)
  File "bji.py", line 53, in handle_job
    self.jobs[jobid] = JIndicator(jobid, state, self.close_callback)
  File "/home/pollinta/Desktop/batch-job-indicator/jindicator.py", line 52, in __init__
    "Job-Indicator", _get_icon(state), category=appindicator.IndicatorCategory.APPLICATION_STATUS)
TypeError: Argument 1 does not allow None as a value
```

**Comment by hirschsn** [comment]
Thanks. A bunch of missing returns...
